# agent/seat_gnome.py
"""Headless GNOME seat: a real gnome-shell on its own session bus, captured by
selkies 2.0 through xdg-desktop-portal (spec §5.1).

The activation env MUST be set before anything can activate a portal: an
inherited DISPLAY makes the consent dialog appear on the physical desktop."""
import os
import re
import shlex
import shutil
import signal
import subprocess
import time
from pathlib import Path

SOCKET = "styx-seat-0"
MIN_GNOME = 46
_SCRUB = ("DISPLAY", "WAYLAND_DISPLAY", "XAUTHORITY", "DBUS_SESSION_BUS_ADDRESS",
          "XDG_SESSION_ID", "GNOME_SETUP_DISPLAY", "SESSION_MANAGER",
          "WAYLAND_SOCKET", "GDK_BACKEND", "QT_QPA_PLATFORM", "DESKTOP_SESSION",
          "XDG_SEAT", "XDG_VTNR", "XDG_SESSION_CLASS")


def build_launch_script(width: int, height: int, sink: str, bus_file: str) -> str:
    sink, bus_file = shlex.quote(sink), shlex.quote(bus_file)
    return "\n".join([
        "#!/bin/bash",
        "# generated by styx-agent: headless GNOME seat (do not edit)",
        "unset DISPLAY WAYLAND_DISPLAY XAUTHORITY",
        "export XDG_SESSION_TYPE=wayland XDG_CURRENT_DESKTOP=ubuntu:GNOME "
        "XDG_SESSION_DESKTOP=ubuntu GNOME_SHELL_SESSION_MODE=ubuntu",
        f"export PULSE_SINK={sink}",
        f"dbus-update-activation-environment DISPLAY= WAYLAND_DISPLAY={SOCKET} "
        f"XDG_SESSION_TYPE=wayland XDG_CURRENT_DESKTOP=ubuntu:GNOME PULSE_SINK={sink}",
        f'echo "$DBUS_SESSION_BUS_ADDRESS" > {bus_file}',
        f"exec gnome-shell --headless --wayland --no-x11 "
        f"--virtual-monitor {width}x{height} --wayland-display={SOCKET}",
        "",
    ])


def gnome_available() -> tuple[bool, str]:
    if not shutil.which("gnome-shell"):
        return False, "gnome-shell not installed"
    try:
        out = subprocess.run(["gnome-shell", "--version"], capture_output=True,
                             text=True, timeout=10).stdout
    except (OSError, subprocess.TimeoutExpired) as e:
        return False, f"gnome-shell --version failed: {e}"
    m = re.search(r"(\d+)\.", out)
    if not m or int(m.group(1)) < MIN_GNOME:
        return False, f"GNOME Shell {MIN_GNOME}+ required (found: {out.strip()})"
    return True, ""


# GNOME seat consent (spec §5.4/§5.5): the portal's restore token is written
# after the one-time grant; without it a frameless viewer is a pending dialog.
CONSENT_PENDING_S = 20
TOKEN_PATH = Path.home() / ".local/state/pixelflux/portal-restore-token"
CONSENT_ERROR = ("GNOME seat needs one-time screen-share consent: run "
                 "'styx-agent doctor --grant' on the box")


def pick_seat_shell(cfg: dict) -> str:
    if cfg.get("mode") != "seat":
        return "mirror"
    want = (cfg.get("stream_settings") or {}).get("seat_shell", "gnome")
    if want == "gnome":
        ok, why = gnome_available()
        if ok:
            return "gnome"
        print(f"GNOME seat unavailable ({why}); using labwc seat", flush=True)
    return "labwc"


def needs_consent(starving_s: float | None, token_path: Path | None = None) -> bool:
    return (starving_s is not None and starving_s >= CONSENT_PENDING_S
            and not (token_path or TOKEN_PATH).exists())


class Escalation:
    """N engine restarts inside a window -> restart the whole seat (spec §5.4)."""
    def __init__(self, limit: int = 3, window_s: float = 600):
        self.limit, self.window_s, self.times = limit, window_s, []

    def record(self, now: float) -> bool:
        self.times = [t for t in self.times if now - t < self.window_s] + [now]
        if len(self.times) >= self.limit:
            self.times = []
            return True
        return False


class GnomeSeat:
    def __init__(self, install_dir: Path, runtime_dir: str, log):
        self.install_dir = Path(install_dir)
        self.runtime_dir = runtime_dir
        self.log = log
        self.bus_file = self.install_dir / "gnome-bus.addr"
        self.script = self.install_dir / "gnome-seat.sh"
        self.bus: str | None = None
        self.restarts = 0
        self._proc = None
        self._started = False

    def start(self, width: int, height: int) -> None:
        from engine import SEAT_SINK
        if self.alive():
            self.stop()
        if self._started:
            self.restarts += 1
        self._started = True
        self.bus = None
        self.bus_file.unlink(missing_ok=True)
        for n in (SOCKET, SOCKET + ".lock"):
            Path(self.runtime_dir, n).unlink(missing_ok=True)
        self.script.write_text(build_launch_script(width, height, SEAT_SINK,
                                                   str(self.bus_file)))
        self.script.chmod(0o700)
        env = {k: v for k, v in os.environ.items() if k not in _SCRUB}
        env["XDG_RUNTIME_DIR"] = self.runtime_dir
        self._proc = subprocess.Popen(["dbus-run-session", "--", str(self.script)],
                                      env=env, stdout=self.log, stderr=self.log,
                                      start_new_session=True)

    def _shell_answers(self) -> bool:
        env = {k: v for k, v in os.environ.items()
               if k not in ("DISPLAY", "WAYLAND_DISPLAY")}
        env["DBUS_SESSION_BUS_ADDRESS"] = self.bus or ""
        try:
            r = subprocess.run(
                ["gdbus", "call", "--session", "-d", "org.gnome.Shell", "-o",
                 "/org/gnome/Shell", "-m", "org.freedesktop.DBus.Peer.Ping"],
                env=env, capture_output=True, timeout=5)
        except (subprocess.TimeoutExpired, OSError):
            return False
        return r.returncode == 0

    def ready(self, timeout: float = 20) -> bool:
        deadline = time.monotonic() + timeout
        while time.monotonic() < deadline:
            if not self.alive():
                return False
            if self.bus is None and self.bus_file.exists():
                self.bus = self.bus_file.read_text().strip() or None
            if (self.bus and Path(self.runtime_dir, SOCKET).exists()
                    and self._shell_answers()):
                return True
            time.sleep(0.1)
        return False

    def alive(self) -> bool:
        return self._proc is not None and self._proc.poll() is None

    def info(self) -> dict:
        return {"socket": SOCKET, "bus": self.bus}

    def stop(self) -> None:
        p = self._proc
        if p is not None and p.poll() is None:
            # dbus-run-session does not forward signals: kill the whole group
            try:
                os.killpg(p.pid, signal.SIGTERM)
                try:
                    p.wait(timeout=15)
                except subprocess.TimeoutExpired:
                    os.killpg(p.pid, signal.SIGKILL)
                    p.wait()
            except ProcessLookupError:
                pass
        self._proc = None
