# agent/seat_gnome.py
"""Headless GNOME seat: a real gnome-shell on its own session bus, captured by
selkies 2.0 through xdg-desktop-portal (spec §5.1).

The activation env MUST be set before anything can activate a portal; the seat
routes ScreenCast/RemoteDesktop to our own consent-free backend (seat_portal.py),
selected through XDG_DESKTOP_PORTAL_DIR."""
import os
import re
import shlex
import shutil
import signal
import subprocess
import time
from pathlib import Path

import refit

SOCKET = "styx-seat-0"
MIN_GNOME = 46
SYS_PYTHON = "/usr/bin/python3"
HELPER_READY_S = 10
PORTAL_SRC = Path("/usr/share/xdg-desktop-portal/portals")
STYX_PORTAL = ("[portal]\nDBusName=org.freedesktop.impl.portal.desktop.styx\n"
               "Interfaces=org.freedesktop.impl.portal.ScreenCast;"
               "org.freedesktop.impl.portal.RemoteDesktop;\nUseIn=gnome\n")
PORTALS_CONF = ("[preferred]\ndefault=gnome;gtk;\n"
                "org.freedesktop.impl.portal.Secret=gnome-keyring;\n"
                "org.freedesktop.impl.portal.ScreenCast=styx;\n"
                "org.freedesktop.impl.portal.RemoteDesktop=styx;\n")
_HELPER_DEPS = ("import dbus, gi; gi.require_version('Gst', '1.0'); "
                "from gi.repository import Gst; Gst.init(None); "
                "assert Gst.ElementFactory.find('pipewiresrc')")
_SCRUB = ("DISPLAY", "WAYLAND_DISPLAY", "XAUTHORITY", "DBUS_SESSION_BUS_ADDRESS",
          "XDG_SESSION_ID", "GNOME_SETUP_DISPLAY", "SESSION_MANAGER",
          "WAYLAND_SOCKET", "GDK_BACKEND", "QT_QPA_PLATFORM", "DESKTOP_SESSION",
          "XDG_SEAT", "XDG_VTNR", "XDG_SESSION_CLASS")


def write_portal_dir(d: Path, src: Path = PORTAL_SRC) -> None:
    """Portal dir for the seat's frontend: the distro's backends plus ours,
    with ScreenCast/RemoteDesktop routed to styx (the frontend reads
    portals.conf from XDG_DESKTOP_PORTAL_DIR)."""
    d.mkdir(parents=True, exist_ok=True)
    for p in src.glob("*.portal"):
        if p.name != "styx.portal":
            shutil.copy(p, d / p.name)
    (d / "styx.portal").write_text(STYX_PORTAL)
    for name in ("portals.conf", "ubuntu-portals.conf", "gnome-portals.conf"):
        (d / name).write_text(PORTALS_CONF)


def build_launch_script(sink: str, bus_file: str, portal_dir: str) -> str:
    sink, bus_file, portal_dir = (shlex.quote(v) for v in (sink, bus_file, portal_dir))
    return "\n".join([
        "#!/bin/bash",
        "# generated by styx-agent: headless GNOME seat (do not edit)",
        "unset DISPLAY WAYLAND_DISPLAY XAUTHORITY",
        "export XDG_SESSION_TYPE=wayland XDG_CURRENT_DESKTOP=ubuntu:GNOME "
        "XDG_SESSION_DESKTOP=ubuntu GNOME_SHELL_SESSION_MODE=ubuntu",
        f"export PULSE_SINK={sink}",
        f"export XDG_DESKTOP_PORTAL_DIR={portal_dir}",
        f"dbus-update-activation-environment DISPLAY= WAYLAND_DISPLAY={SOCKET} "
        f"XDG_SESSION_TYPE=wayland XDG_CURRENT_DESKTOP=ubuntu:GNOME PULSE_SINK={sink} "
        f"XDG_DESKTOP_PORTAL_DIR={portal_dir}",
        f'echo "$DBUS_SESSION_BUS_ADDRESS" > {bus_file}',
        # No --virtual-monitor: seat_portal.py owns the monitor and its size.
        f"exec gnome-shell --headless --wayland --no-x11 --wayland-display={SOCKET}",
        "",
    ])


def gnome_available() -> tuple[bool, str]:
    if not shutil.which("gnome-shell"):
        return False, "gnome-shell not installed"
    try:
        out = subprocess.run(["gnome-shell", "--version"], capture_output=True,
                             text=True, timeout=10).stdout
    except (OSError, subprocess.TimeoutExpired) as e:
        return False, f"gnome-shell --version failed: {e}"
    m = re.search(r"(\d+)\.", out)
    if not m or int(m.group(1)) < MIN_GNOME:
        return False, f"GNOME Shell {MIN_GNOME}+ required (found: {out.strip()})"
    try:
        rc = subprocess.run([SYS_PYTHON, "-c", _HELPER_DEPS], capture_output=True,
                            timeout=20).returncode
    except (OSError, subprocess.TimeoutExpired):
        rc = 1
    if rc:
        return False, "seat helper deps missing (python3-dbus, python3-gi, gstreamer1.0-pipewire)"
    return True, ""


def pick_seat_shell(cfg: dict) -> str:
    if cfg.get("mode") != "seat":
        return "mirror"
    want = (cfg.get("stream_settings") or {}).get("seat_shell", "gnome")
    if want == "gnome":
        ok, why = gnome_available()
        if ok:
            return "gnome"
        print(f"GNOME seat unavailable ({why}); using labwc seat", flush=True)
    return "labwc"


class Escalation:
    """N engine restarts inside a window -> restart the whole seat (spec §5.4)."""
    def __init__(self, limit: int = 3, window_s: float = 600):
        self.limit, self.window_s, self.times = limit, window_s, []

    def record(self, now: float) -> bool:
        self.times = [t for t in self.times if now - t < self.window_s] + [now]
        if len(self.times) >= self.limit:
            self.times = []
            return True
        return False


class GnomeSeat:
    def __init__(self, install_dir: Path, runtime_dir: str, log):
        self.install_dir = Path(install_dir)
        self.runtime_dir = runtime_dir
        self.log = log
        self.bus_file = self.install_dir / "gnome-bus.addr"
        self.script = self.install_dir / "gnome-seat.sh"
        self.bus: str | None = None
        self.restarts = 0
        self._proc = None
        self._started = False
        self.portal_dir = self.install_dir / "portals"
        self.size_file = self.install_dir / "seat-size"
        self.ready_file = Path(runtime_dir) / "styx-seat-portal.ready"
        self.size: tuple[int, int] | None = None
        self._helper = None
        self._heal = False

    def start(self, width: int, height: int) -> None:
        from engine import SEAT_SINK
        if (self._proc is not None and self._proc.poll() is None
                and self._helper is not None and self._helper.poll() is not None):
            # Only the helper died (e.g. GNOME's screen-share Stop closed the
            # virtual monitor): keep GNOME and its windows; ready() re-arms it.
            self._heal = True
            return
        if self.alive():
            self.stop()
        if self._started:
            self.restarts += 1
        self._started = True
        self.size = (width, height)
        self.bus = None
        self.bus_file.unlink(missing_ok=True)
        for n in (SOCKET, SOCKET + ".lock"):
            Path(self.runtime_dir, n).unlink(missing_ok=True)
        write_portal_dir(self.portal_dir)
        self.script.write_text(build_launch_script(SEAT_SINK, str(self.bus_file),
                                                   str(self.portal_dir)))
        self.script.chmod(0o700)
        env = {k: v for k, v in os.environ.items() if k not in _SCRUB}
        env["XDG_RUNTIME_DIR"] = self.runtime_dir
        self._proc = subprocess.Popen(["dbus-run-session", "--", str(self.script)],
                                      env=env, stdout=self.log, stderr=self.log,
                                      start_new_session=True)

    def _shell_answers(self) -> bool:
        env = {k: v for k, v in os.environ.items()
               if k not in ("DISPLAY", "WAYLAND_DISPLAY")}
        env["DBUS_SESSION_BUS_ADDRESS"] = self.bus or ""
        try:
            r = subprocess.run(
                ["gdbus", "call", "--session", "-d", "org.gnome.Shell", "-o",
                 "/org/gnome/Shell", "-m", "org.freedesktop.DBus.Peer.Ping"],
                env=env, capture_output=True, timeout=5)
        except (subprocess.TimeoutExpired, OSError):
            return False
        return r.returncode == 0

    def ready(self, timeout: float = 20) -> bool:
        if self._heal:
            self._heal = False
            return self._start_helper(*self.size)
        deadline = time.monotonic() + timeout
        while time.monotonic() < deadline:
            if not self.alive():
                return False
            if self.bus is None and self.bus_file.exists():
                self.bus = self.bus_file.read_text().strip() or None
            if (self.bus and Path(self.runtime_dir, SOCKET).exists()
                    and self._shell_answers()):
                return self._start_helper(*self.size)
            time.sleep(0.1)
        return False

    def alive(self) -> bool:
        """GNOME up and, once started, the seat helper too (it owns the monitor
        and the portal backend; without it capture and input are dead)."""
        return (self._proc is not None and self._proc.poll() is None
                and (self._helper is None or self._helper.poll() is None))

    def _spawn_helper(self, w: int, h: int):
        env = {k: v for k, v in os.environ.items() if k not in _SCRUB}
        env.update({"XDG_RUNTIME_DIR": self.runtime_dir,
                    "DBUS_SESSION_BUS_ADDRESS": self.bus or "",
                    "XDG_DESKTOP_PORTAL_DIR": str(self.portal_dir),
                    "XDG_CURRENT_DESKTOP": "ubuntu:GNOME", "XDG_SESSION_TYPE": "wayland",
                    "STYX_PORTAL_READY": str(self.ready_file)})
        return subprocess.Popen([SYS_PYTHON, str(self.install_dir / "seat_portal.py"),
                                 f"{w}x{h}"], env=env, stdout=self.log, stderr=self.log,
                                start_new_session=True)

    def _start_helper(self, w: int, h: int) -> bool:
        """(Re)start the helper at w x h; True once it reports that size live."""
        self._stop_helper()
        self.ready_file.unlink(missing_ok=True)
        self._helper = self._spawn_helper(w, h)
        deadline = time.monotonic() + HELPER_READY_S
        while time.monotonic() < deadline:
            if self._helper.poll() is not None:
                return False
            try:
                if self.ready_file.read_text().strip() == f"{w}x{h}":
                    self.size = (w, h)
                    refit.write_size(self.size_file, w, h)
                    return True
            except OSError:
                pass
            time.sleep(0.1)
        self._stop_helper()
        return False

    def refit(self, w: int, h: int) -> bool:
        """New monitor size = new helper. On failure fall back to the old size so
        the seat is never left monitorless. Caller stops selkies first."""
        old = self.size
        if self._start_helper(w, h):
            return True
        if old:
            self._start_helper(*old)
        return False

    def _stop_helper(self) -> None:
        p, self._helper = self._helper, None
        if p is None or p.poll() is not None:
            return
        try:
            os.killpg(p.pid, signal.SIGTERM)
            try:
                p.wait(timeout=10)
            except subprocess.TimeoutExpired:
                os.killpg(p.pid, signal.SIGKILL)
                p.wait()
        except ProcessLookupError:
            pass

    def info(self) -> dict:
        return {"socket": SOCKET, "bus": self.bus}

    def stop(self) -> None:
        self._stop_helper()
        p = self._proc
        if p is not None and p.poll() is None:
            # dbus-run-session does not forward signals: kill the whole group
            try:
                os.killpg(p.pid, signal.SIGTERM)
                try:
                    p.wait(timeout=15)
                except subprocess.TimeoutExpired:
                    os.killpg(p.pid, signal.SIGKILL)
                    p.wait()
            except ProcessLookupError:
                pass
        self._proc = None
